-- MySQL Script generated by MySQL Workbench
-- Tue Sep 13 11:21:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema practicasiniciales-p4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema practicasiniciales-p4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `practicasiniciales-p4` ;
USE `practicasiniciales-p4` ;

-- -----------------------------------------------------
-- Table `practicasiniciales-p4`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicasiniciales-p4`.`cursos` (
  `idcursos` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `creditos_necesarios` INT NOT NULL,
  PRIMARY KEY (`idcursos`),
  UNIQUE INDEX `idcursos_UNIQUE` (`idcursos` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `practicasiniciales-p4`.`cursosaprobados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicasiniciales-p4`.`cursosaprobados` (
  `idcursosaprobados` INT NOT NULL AUTO_INCREMENT,
  `idcurso` INT NOT NULL,
  `punteo` INT NOT NULL,
  PRIMARY KEY (`idcursosaprobados`),
  INDEX `idcursos_idx` (`idcurso` ASC) ,
  CONSTRAINT `idcursos`
    FOREIGN KEY (`idcurso`)
    REFERENCES `practicasiniciales-p4`.`cursos` (`idcursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practicasiniciales-p4`.`credenciales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicasiniciales-p4`.`credenciales` (
  `carnet` INT NOT NULL,
  `1apellido` VARCHAR(45) NOT NULL,
  `2apellido` VARCHAR(45) NULL DEFAULT NULL,
  `1nombre` VARCHAR(45) NOT NULL,
  `2nombre` VARCHAR(45) NULL DEFAULT NULL,
  `contrasena` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `idcursosaprobados` INT NOT NULL,
  PRIMARY KEY (`carnet`),
  UNIQUE INDEX `carnet_UNIQUE` (`carnet` ASC) ,
  INDEX `idcursosaprobados_idx` (`idcursosaprobados` ASC) ,
  CONSTRAINT `idcursosaprobados`
    FOREIGN KEY (`idcursosaprobados`)
    REFERENCES `practicasiniciales-p4`.`cursosaprobados` (`idcursosaprobados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `practicasiniciales-p4`.`publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicasiniciales-p4`.`publicaciones` (
  `idpublicaciones` INT NOT NULL,
  `carne` INT NOT NULL,
  `mensaje` VARCHAR(500) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idpublicaciones`),
  INDEX `carne_idx` (`carne` ASC),
  CONSTRAINT `carne`
    FOREIGN KEY (`carne`)
    REFERENCES `practicasiniciales-p4`.`credenciales` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `practicasiniciales-p4`.`comentariospublicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practicasiniciales-p4`.`comentariospublicacion` (
  `idcomentario` INT NOT NULL,
  `idpublicacion` INT NOT NULL,
  `comentario` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idcomentario`),
  INDEX `idpublicacion_idx` (`idpublicacion` ASC),
  CONSTRAINT `idpublicacion`
    FOREIGN KEY (`idpublicacion`)
    REFERENCES `practicasiniciales-p4`.`publicaciones` (`idpublicaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
